AWSTemplateFormatVersion: 2010-09-09
Description: Creating Management Event Trail

Parameters: 
  ManagementEventTrailBucketName:
    Type: String
  TrailLogGroupName:
    Type: String
  TrailLogStreamName:
    Type: String
Resources: 

  ManagementEventTrailBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref ManagementEventTrailBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      # trailのロックはかけたほうがいい
      # ObjectLockConfiguration:
      #   ObjectLockConfiguration
      # ObjectLockEnabled: Boolean
  
  # loggroup
  TrailLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName: !Ref TrailLogGroupName
      # ログデータの暗号化をする
      #KmsKeyId: String
      RetentionInDays: 365
  
  # KMS
  # rogrole
  TrailServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: TrailServiceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TrailLogPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub
                  - arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${TrailLogGroupName}:log-stream:${TrailLogStreamName}*
                  - TrailLogGroupName: !Ref TrailLogGroupName
                    TrailLogStreamName: !Ref TrailLogStreamName


  # ManagementEventTrail:
  #   Type: AWS::CloudTrail::Trail
  #   Properties:
  #     TrailName: ManagementEventTrail
  #     IsMultiRegionTrail: true 
  #     IncludeGlobalServiceEvents: true
  #     S3BucketName: !Ref ManagementEventTrailBucket
  #     EnableLogFileValidation: true
  #     KMSKeyId: 
  #     CloudWatchLogsLogGroupArn: 
  #     CloudWatchLogsRoleArn: 
  #     EventSelectors: 
  #       - ReadWriteType: All
  #         IncludeManagementEvents: true
  #     IsLogging: true

