AWSTemplateFormatVersion: 2010-09-09
Description: Creating Management Event Trail

Parameters: 
  ManagementEventTrailBucketName:
    Type: String
  TrailLogGroupName:
    Type: String
  # TrailLogStreamName:
  #   Type: String
  TrailName:
    Type: String

Resources: 

  ManagementEventTrailBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref ManagementEventTrailBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      # trailのロックはかけたほうがいい
      # ObjectLockConfiguration:
      #   ObjectLockConfiguration
      # ObjectLockEnabled: Boolean
  
  TrailBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref ManagementEventTrailBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: Allow CloudTrail to check bucket acl
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource: !Sub 
            - "arn:aws:s3:::${TrailBucketName}"
            - TrailBucketName: !Ref ManagementEventTrailBucketName
        - Sid: Allow CloudTrail to put object
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:PutObject
          Resource: !Sub 
            - "arn:aws:s3:::${TrailBucketName}/AWSLogs/${AWS::AccountId}/*"
            - TrailBucketName: !Ref ManagementEventTrailBucketName
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
  

  TrailLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName: !Ref TrailLogGroupName
      # ログデータの暗号化をする
      #KmsKeyId: String
      RetentionInDays: 365
  
  TrailServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: TrailServiceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TrailLogPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt TrailLogGroup.Arn


  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Ref TrailName
      IsMultiRegionTrail: true 
      IncludeGlobalServiceEvents: true
      S3BucketName: !Ref ManagementEventTrailBucketName
      EnableLogFileValidation: true
      CloudWatchLogsLogGroupArn: !GetAtt TrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt TrailServiceRole.Arn
      EventSelectors: 
        - ReadWriteType: All
          IncludeManagementEvents: true
      IsLogging: true

